language: node_js
node_js:
  - stable
  - 6
cache: yarn
install: yarn --ignore-engines # ignore engines to test node 6, otherwise it fails on engine check
script:
  - travis-github-status lint flow jest snyk codeclimate
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5156be73e058008e1ed2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
