version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
           name: Run lint
           command: npm run lint
      - run:
         name: Run unit test
         command: npm run test
#  surge:
#     docker:
#       - image: circleci/node:8.5
#     working_directory: ~/repo
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run build
#       - run: npm run deploy-surge -- -d seek-asia-style-guide--$CIRCLE_SHA1.surge.sh
  deploy:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run prepublish
#      - run: npm run semantic-release
workflows:
  version: 2
  status-check:
    jobs:
      - build:
          filters:
            branches:
              ignore: rudy
#      - surge:
#          requires:
#            - build
#          filters:
#            branches:
#              ignore: master
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: rudy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: rudy
